### ISSUE TITLE
Mudar banco de dados

### ISSUE THREAD

**Issue by guilhermebr** [piratas/apoio-piratas#12]
@desci Qual banco de dados podemos usar em production?
O servidor tem Docker? se tiver podemos subir o banco em um container que ai não influencia em outros serviços, nem demanda instalação.

**Comment by iuriguilherme** [comment]
@guilhermebr Postgres ou mysql, tem que ter sudo

**Comment by iuriguilherme** [comment]
@guilhermebr Ainda não tem docker, eu to tentando escolher uma solução de virtualização também sem ser Xen.
Provavelmente vou botar LXC se nada der certo, porque ta tudo rodando no bare metal.

**Comment by carloscosta** [comment]
@desci @guilhermebr temos outro server? 

rodar um Postgree/MySQL no mesmo host onde tá o Web Server não é boa prática tanto do ponto de vista da performance quanto da segurança http://stackoverflow.com/a/660036

**Comment by iuriguilherme** [comment]
@carloscosta por hora isso vai ter que ser na má prática mesmo.
eu vou instalar assim que possível neste servidor alguma ferramenta de virtualização (lxc, openvz, kvm), tem que cuidar esse servidor que é o único funcional disponível hoje, e eu faço backup tudo na mão.

**Comment by carloscosta** [comment]
Tô organizando pra fazer um release, pretendo incluir essa issue. 
O RDBMS a ser adotado será postgresql.

**Comment by gilsondev** [comment]
Pode usar o docker para container. Nesse caso poderia ser da seguinte forma:
- Docker da aplicação (Ubuntu + Python + Aplicação);
- Docker do banco de dados (PostgreSQL);
- Docker do servidor web (Nginx);

O nosso amigo @gomex acabei de criar uma PR para iniciar algumas melhorias com o docker que é a #21.

Assim, pode usar as boas práticas de configuração de ambiente como o [12factors](https://12factor.net/) como por exemplo, atribuição de valores de configuração via variáveis de ambiente.

Vou fazer algumas refatorações e vou enviar via PR para darem uma olhada, e na descrição do porque de cada uma.

**Comment by iuriguilherme** [comment]
Alguém ta usando o postgres no _entwickler_?

**Comment by carloscosta** [comment]
@desci não. Alias, essa issue nem faz tanto sentido assim. Não tem funcionalidade no site que precise de banco de dados - tem a mini FAQ, mas o site tá no ar por vários e _nenhuma_ pergunta foi submetida.

Como desenvolvedor principal do site, e responsável pelo v2, vou fechar a issue.
