### ISSUE TITLE
Organizar branches

### ISSUE THREAD

**Issue by iuriguilherme** [piratas/apoio-piratas#15]
Estou olhando aqui no servidor e sugiro que o site de produção não se atualize pela branch `master`.

Proponho que o site oficial `apoio.partidopirata.org` se atualize a partir de algum outro ramo. No [site do iuf](https://notabug.org/piratas/desgovernanca-site) eu usava o ramo/branch `oficial`, sendo `master` o ramo/branch que atualizava o site de homologação e testes.

Temos os seguintes domínios bem configurados com SSL:
- https://apoio.partidopirata.org **site oficial**
- https://apoio.partidopirata.xyz
- https://apoio.pirata.xyz
- https://apoio.piratas.xyz
- https://apoio-dev.partidopirata.org
- https://apoio-dev.partidopirata.xyz
- https://apoio-dev.pirata.xyz
- https://apoio-dev.piratas.xyz
- https://apoiar.partidopirata.org
- https://apoiar.partidopirata.xyz
- https://apoiar.pirata.xyz
- https://apoiar.piratas.xyz
- https://apoiar-dev.partidopirata.org
- https://apoiar-dev.partidopirata.xyz
- https://apoiar-dev.pirata.xyz
- https://apoiar-dev.piratas.xyz

Todos outros sem ser o primeiro podem ser utilizados para testes, inclusive é possível criar mais subdomínios, se for necessário.

**Comment by carloscosta** [comment]
This one was done by @desci 
Thanks!

**Comment by iuriguilherme** [comment]
Pra registrar, o site **apoio.partidopirata.org** está no ramo _oficial_ e o site **apoio.partidopirata.xyz** está no ramo _dev_.

Todos outros devem estar no ramo _master_.
