### ISSUE TITLE
Links diretos para Estatuto e Programa

### ISSUE THREAD

**Issue by prenass** [piratas/apoio-piratas#17]
Entendo ser crucial que o site de apoio tenha links diretos para o [estatuto](http://partidopirata.org/documentos/estatuto/) e o [programa](http://partidopirata.org/quem-somos/estrutura-nacional/documentos/programa/) do Partido Pirata. Conversei brevemente com o @carloscosta pelo Telegram no Lounge e criei essa pendência.
- [x] De forma urgente, incluir no menu superior dois links, um para cada documento, redirecionando diretamente a navegação para cada um dos respectivos contéudos específicos no site principal.
- [ ] Como tarefa completa, creio que a solução seja criar botões particulares e que o próprio site do apoio conte com um conteúdo próprio do Estatuto e do Programa, talvez até com uma diagramação mais amigável à leitura humana.

**Comment by carloscosta** [comment]
I'm on this.

**Comment by carloscosta** [comment]
Done. 
Thank you for your suggestion :-)

**Comment by iuriguilherme** [comment]
"Tarefa completa"

**Comment by carloscosta** [comment]
Bom, não entendi porque foi reaberto.
Está tarefa está completa.

**Comment by iuriguilherme** [comment]
Está no OP, colocar o texto do estatuto e o programa no site

**Comment by carloscosta** [comment]
Discordo. Não vejo necessidade de duplicar o texto entre os sites. O link foi suficiente.
