### ISSUE TITLE
Vocês tornaram PÚBLICA a secret_key da produção!

### ISSUE THREAD

**Issue by rsip22** [piratas/apoio-piratas#23]
**# SECURITY WARNING: keep the secret key used in production secret!**
SECRET_KEY = '&dpi7e#h80%yz!rpnt3i=(w@!za0+h3s856rr91s2s2w4qwp7j'

Arquivo: https://github.com/piratas/apoio-piratas/blob/master/apoio/apoio/settings.py

**Comment by carloscosta** [comment]
Fixado em https://github.com/piratas/apoio-piratas/pull/22

**Comment by iuriguilherme** [comment]
Gerador de chave "secreta": https://notabug.org/desci/scripts/src/master/random.py
