### ISSUE TITLE
Alterar "fale conosco"

### ISSUE THREAD

**Issue by iuriguilherme** [piratas/apoio-piratas#25]
@gal_dino no telegram sugeriu alterar texto da parte "fale conosco" de:

```
Contamos com a vossa colaboração para atingir a cota determinada pela legislação eleitoral e fazer com que os PIRATAS representem você no cenário político nacional. 

O Comitê Nacional da nossa campanha de coleta mantém um grupo Telegram, entre em contato conosco:
https://telegram.me/apoiopirata
```

para:

```
* Contamos com sua colaboração para atingir a cota determinada pela legislação eleitoral e fazer com que o PIRATAS abra mais essa frente de atuação!

* O Comitê Nacional da nossa campanha de coleta mantém um grupo no Telegram, entre em contato conosco:
https://telegram.me/coletapirata
```

**Comment by iuriguilherme** [comment]
@gal_dino esclareceu que na verdade isto é pedido do GTC como condição necessária para divulgar o [site de apoio](https://apoio.partidopirata.org) no [site do partido](http://partidopirata.org).

**Comment by kannonsan** [comment]
Em "COMO DAR SEU APOIO" a sugestão é modificar a frase:

> Contamos com a vossa colaboração para atingir a cota determinada pela legislação eleitoral e fazer com que os PIRATAS representem você no cenário político nacional. 

por

> **“Contamos com sua colaboração para atingir a cota determinada pela legislação eleitoral e fazer com que o PIRATAS abra mais essa frente de atuação!”**

Justificativa: a mudança sugerida é pq a expressão usada vai contra a ideia do partido pirata de democracia liquida e participação direta da população, mesmo que através de uma "representação" formal. A mudança é para se adequar ao nosso programa, nossos princípios e tbm constituir maior harmonização com estilo de redação .

**Comment by carloscosta** [comment]
Feito, ver commit:

https://github.com/piratas/apoio-piratas/commit/aaac27a42f1ddcebcdb84cf364deb0745ccc4781

Obrigado!
