### ISSUE TITLE
Sugestões de modificações no site

### ISSUE THREAD

**Issue by kannonsan** [piratas/apoio-piratas#26]
1) **TEXTO PRINCIPAL**

Em "COMO DAR SEU APOIO" a sugestão é modificar a frase:

> Contamos com a vossa colaboração para atingir a cota determinada pela legislação eleitoral e fazer com que os PIRATAS representem você no cenário político nacional. 

por

> **“Contamos com sua colaboração para atingir a cota determinada pela legislação eleitoral e fazer com que o PIRATAS abra mais essa frente de atuação!”**

Justificativa: a mudança sugerida é pq a expressão usada vai contra a ideia do partido pirata de democracia liquida e participação direta da população, mesmo que através de uma "representação" formal. A mudança é para se adequar ao nosso programa e nossos princípios e tbm constituir maior harmonização com estilo de redação .

2) **Fale conosco**

A sugestão é:

> O Comitê Nacional da nossa campanha de coleta mantém um grupo Telegram, entre em contato conosco:
> https://telegram.me/apoiopirata”

por:
_**“O Comitê Nacional da nossa campanha de coleta mantém um grupo no Telegram, entre em contato conosco:
https://telegram.me/coletapirata”**_ 

Justificativa: tivemos no passado problemas com grupos divulgados nos meios oficiais, não administrados pelo GTC e que posteriormente se perdem ou são mal administrados. A sugestão aqui é colocar um grupo administrado colegiadamente pelo GTC e acrescentando a essa administração pessoas que estão a frente do GTI e do projeto de Apoio de Coleta, como o Desci. O grupo "coletapirata" no Telegram foi criado prontamente após a desativação do antigo grupo e conta com administração dos secretários e membros do GTC, aguardando membros do GTI para também ficarem a cargo da administração. 

3) **Seja um coletor**

É preciso avisar para as pessoas que tudo bem elas coletarem assinaturas. Mas apenas os coletores oficiais registrados no TSE podem fazer tal tarefa. De fato, o espaço "coletor" na ficha deve ficar em branco, por isso pode haver tal confusão. Se for assinado por um coletor não cadastrado no TSE, a ficha será invalidada. É preciso enviar um email para secretaria geral para pedir para se tornar um coletor: não é apenas querer e sair assinando!

4) **Endereço para Envio** #27 

Em nenhum momento é dito o que fazer com as fichas. Apenas diz para assiná-las. Todos questionarão: e agora o que eu faço? Precisamos definir ao menos uma Caixa Postal para isso. Temos utilizado ao longo de um certo tempo o endereço de Brasília como local para envio, segundo o site oficial do partido pirata org. Podemos listar os coletores oficializados e pedir para as pessoas enviarem para eles. É uma outra questão. Mas se queremos isso para ontem, melhor por ao menos um endereço já.

5) **FAQ** #6 

FAQ é um acrónimo da expressão inglesa Frequently Asked Questions, que pode ser traduzido por «Perguntas Mais Frequentes». É interessante o sistema que vocês pensaram. Mas devemos por de fato as perguntas frequentes para que não tenhamos que responder a todos que acessem o site. Talvez essas questões devessem estar mais a mostra no site. Não sei.

Abaixo perguntas frequentes que são feitas nos grupos e canais do Partido Pirata sobre coleta de assinaturas.

**E esse espaço para o dedão? É preciso por o meu dedão?** 
O espaço para o dedão é apenas para apoiadores analfabetos. Não é preciso utilizar esse espaço caso você esteja lendo esse texto. 

**E o espaço para coletor? Devo assinar o que?**
O espaço do coletor deve permanecer em branco. Ele só poderá ser preenchido pelos coletores piratas cadastrados no TSE. Se for assinado por um coletor não cadastrado será invalidado.

**Eu sou filiado de outro partido. Posso apoiar?**
Com as atuais regras do TSE apenas pessoas não filiadas de outros partidos podem apoiar. Pretendemos questionar esse ponto em breve para que possamos contar com apoio de qualquer pessoa brasileira, independente de já ter apoiado ou não algum partido.

**Quantos apoios ainda faltam?**
Muitos. (Existe um texto no Hackpad explicando a situação. O ideal é divulgar o site de apoio junto com o texto, escrito por Wilson.)

6) **Formato da Imagem em Destaque** #29

A imagem está muito bonita. Entretanto, para redes sociais, é preciso seguir as especificações. O Coletivo Mineiro compartilhou o link e ficou claro que a imagem está completamente fora das especificações. Acesse o Facebook do coletivo mineiro e vejam. As especificações de imagens em destaque em redes sociais podem ser acessadas no site desenvolvedores.

O site está muito bom, faltando esses pequenos acertos acho que devemos partir para ampla divulgação, falando com os administradores de sites e enviando para um release de imprensa.

PARABÉNS A TODOS!

AHOY!

**Comment by kannonsan** [comment]
Essas sugestões foram feitas ao longo de meses por algumas pessoas no grupo https://telegram.me/GTCvoluntarios e tbm na última reunião do GTC (atas em http://gtc.partidopirata.org) e tbm pitacos meus.

Essas não são mudanças definitivas e não são imposições ou condicionantes para publicação ou para compartilhamento nas redes sociais. Precisamos nos reunir e conversar, sempre que possível melhorar as informações conforme elas vão chegando.

P-)

**Comment by carloscosta** [comment]
Entendo que essa issue tem duas partes:
- Texto em "Como dar seu apoio". Resolvido na issue #25 
- Atualizar link do grupo. Duplicado com #33 

Fechando essa issue por duplicidade. Obrigado!

**Comment by kannonsan** [comment]
Na verdade são seis partes. Algumas duplicadas de fato.

**Comment by kannonsan** [comment]
@carloscosta foram listadas seis partes com seis questionamentos e sugestões para mudanças.
Você não analisa os seis questionamentos e fecha uma "issue" sem que ela tenha sido resolvida.

Como provavelmente não teremos outra saída que não seja na ANAPIRATA rediscutir atribuições do GTI: cara a cara, olho no olho, espero que as coisas funcionem.

Acho lamentável a sua atitude e a de todos os pouquissíssimos envolvidos no site de apoio.

**Comment by carloscosta** [comment]
@kannonsan fique a vontade para fazer as alterações e mandar um patch pro GTI. Eu não me envolvo mais com os Piratas.
