### ISSUE TITLE
Atualizar arte

### ISSUE THREAD

**Issue by iuriguilherme** [piratas/apoio-piratas#29]
O @plasmoide havia enviado arte nova e está perdida em algum grupo de telegram pra variar.

É necessário resgatá-la e atualizar no site.

**Comment by kannonsan** [comment]
![teste23](https://cloud.githubusercontent.com/assets/19435297/17493925/c43fe76e-5d88-11e6-976f-f52c139e46b6.jpg)

Como pode ser visto no Facebook, a imagem está fora dos padrões, ficando cortada.
Mesmo que seja modificada prontamente por uma nova imagem, o Facebook continuará utilizando da imagem errada antiga, pois ela está memorizada, sendo necessário que o administrador da página ou quem for compartilhar que modifique dentro do Facebook antes de publicá-la.

Não se pode esperar que qualquer pessoa faça isso, mas podemos pedir aos administradores de páginas que o façam quando assim forem divulgar.

**Comment by iuriguilherme** [comment]
Eu pedi outra imagem pro @plasmoide e ele mandou em uma proporção que é **quase** 1:1.91

![liberte_democracia_piratas_2](https://cloud.githubusercontent.com/assets/2027447/17494713/567ed902-5d8c-11e6-9192-b0653f4a91a6.jpg)

**Comment by iuriguilherme** [comment]
Eu vou referenciar aqui a documentação que é pra quando alguém for produzir imagens:
- https://developers.facebook.com/docs/sharing/webmasters#images
- https://developers.facebook.com/docs/sharing/best-practices#images

Após correção, atualizar na [ferramenta](https://developers.facebook.com/tools/debug/sharing/).

**Comment by iuriguilherme** [comment]
A partir deste eu não vou mais aceitar trabalho em JPEG, o que não tiver em SVG não vai mais pro site.

**Comment by iuriguilherme** [comment]
Corrigido por c4421573495e74ac49a8f08eaca6891eb6efbf17 de !piratas/assets-piratas

**Comment by iuriguilherme** [comment]
7454b0f40f7bba1c5b57e255dd5a1371d417bb30
