### ISSUE TITLE
Alterar link para grupo de telegram

### ISSUE THREAD

**Issue by iuriguilherme** [piratas/apoio-piratas#33]
Encaminharam duas sugestões já:
1. Alterar o link para https://telegram.me/coletapirata
2. Alterar o link para https://telegram.me/recepcaopirata

A segunda sugestão foi dada pelo @WilsonLC com a seguinte justificativa:

> porque se for o primeiro contato das pessoas com o partido faz sentido ele ter um contato mais amplo com todo mundo  e não apenas com um grupo que discute apenas a coleta de assinaturas

**Comment by iuriguilherme** [comment]
Eu entendo que os grupos de _telegram_ específicos para discussão do apoiamento e coleta de assinaturas foram criados para agregar esforços em relação à campanha de coleta de assinaturas, e não como forma de providenciar um primeiro contato com o partido, portanto discordo da premissa.

**Comment by kannonsan** [comment]
Justificativa: tivemos no passado problemas com grupos divulgados nos meios oficiais, não administrados pelo GTC e que posteriormente se perdem ou são mal administrados. A sugestão aqui é colocar um grupo https://telegram.me/coletapirata administrado colegiadamente pelo GTC e acrescentando a essa administração pessoas que estão a frente do GTI e do projeto de Apoio de Coleta, como o Desci. O grupo "coletapirata" no Telegram foi criado prontamente após a desativação do antigo grupo e conta com administração dos secretários e membros do GTC, aguardando membros do GTI para também ficarem a cargo da administração.

**Comment by carloscosta** [comment]
O fato de existirem o grupo do GTI @apoiopirata e o grupo do GTC @coletapirata demonstra claramente que vocês estão brigando pelo poder, e não pelo Partido.

Eu vou adotar a sensata solução do @WilsonLC de mandar as pessoas para a @recepcaopirata pois lá tem pessoas que ligam pro Partido e querem o sucesso da campanha.

Vide commit:
https://github.com/piratas/apoio-piratas/commit/9b47936d6f1017f75b2402837a4890e9aa298277

Obrigado!

**Comment by kannonsan** [comment]
> O fato de existirem o grupo do GTI @apoiopirata e o grupo do GTC @coletapirata demonstra claramente que vocês estão brigando pelo poder, e não pelo Partido.
> 
> Eu vou adotar a sensata solução do @WilsonLC de mandar as pessoas para a @recepcaopirata pois lá tem pessoas que ligam pro Partido e querem o sucesso da campanha.

No grupo @coletapirata fazem parte Paulo Crosara e Daniel Prazeres -- secretários gerais do Partido Pirata e membros do Grupo de Trabalho Jurídico. Logo, não se trata de o "grupo do GTC". Pode servir como um grupo específico para tratar questões de coleta, de forma interna. Não faço ideia.

O grupo @apoiopirata não faço ideia.

Já o grupo @recepcaopirata é administrado pelo GTC e talvez mais indicado, de fato, para o público em geral.

**Comment by iuriguilherme** [comment]
O 9b47936d6f1017f75b2402837a4890e9aa298277 #35 não vai pro site porque se é pra alterar o grupo de contato para @recepcaopirata, então o contexto do texto auxiliar tem que mudar também.

O propósito do grupo @apoiopirata é o que está escrito no texto auxiliar:

> O Comitê Nacional da nossa campanha de coleta mantém um grupo **Telegram**, entre em contato conosco:

O propósito do grupo @recepcaopirata é receber pessoas interessadas no Partido, independentemente de interesse na organização para a campanha de coleta.

Portanto, não tem como mudar uma coisa sem mudar outra.

**Comment by carloscosta** [comment]
Oi @kannonsan por favor ver se alguém do GTC pode revisar o texto também, para que possamos receber as pessoas na @recepcaopirata. Basta colar o texto aqui que eu prontamente revisarei o código.

Lembrando que por ter 2 grupos, @apoiopirata e @coletapirata, nós chegamos a um impasse. Neste caso @recepcaopirata funcionará como a terceira via.

Caso não revisem o texto, eu farei a revisão do texto eu mesmo, ou removerei completamente o texto e o link para grupos Telegram.

Obrigado!

**Comment by carloscosta** [comment]
Após conversar com o Wilson Lira e o Galdino, o texto foi alterado para:

_Caso queira tirar uma dúvida, contribuir com a campanha ou mesmo conhecer melhor o Partido Pirata, entre em contato através do nosso grupo Telegram_  (aqui o link)

Já fiz commit.

**Comment by kannonsan** [comment]
Bem, na verdade o link foi retirado.
