### ISSUE TITLE
F.A.Q. nova tentativa

### ISSUE THREAD

**Issue by kannonsan** [piratas/apoio-piratas#36]
FAQ é um acrónimo da expressão inglesa Frequently Asked Questions, que pode ser traduzido por «Perguntas Mais Frequentes». 

É preciso atualizar o link: https://apoio.partidopirata.org/faqs/

Abaixo perguntas frequentes que são feitas nos grupos e canais do Partido Pirata sobre coleta de assinaturas.

1) E esse espaço para o dedão? É preciso por o meu dedão? 
R.: Só para pessoas analfabetas. Nesse caso, quem coletar a assinatura preenche os espaços e a pessoa, como não poderá assinar, coloca o dedão, para verificação pela Justiça Eleitoral

2) E o espaço para coletor? Devo assinar o que?
R.:  A pessoa que coletar o apoiamento preenche os espaços e assina. Essa pessoa NÃO PRECISA estar registrada no TSE, nem ser associada ao PIRATAS: pode ser qualquer outra pessoa que não a própria pessoa que assina o apoiamento.

3) Eu sou filiado de outro partido. Posso apoiar?
R.: Não. Apenas se admite "o apoiamento de eleitores não filiados a partido político", conforme o § 1º do art. 7º da  Lei nº 9.096/1995, na redação conferida pela Lei nº Lei nº 13.165/2015.

4) Quantos apoios ainda faltam?
R.: Estima-se que milhares de assinaturas já foram coletadas, mas até o momento nenhum foi inserida no sistema da Justiça Eleitoral e processada completamente (incluindo validação da ficha original assinada pelo cartório eleitoral da respectiva sessão eleitoral). O número pode ser acompanhado no site do TSE http://inter01.tse.jus.br/sapf-consulta/paginas/partidoFormacao/listar.

5) Estou com várias fichas assinadas. O que eu faço?
R.: Por hora, o mais econômico e seguro é manter as fichas consigo e comunicar a quantidade ao coletivo organizado mais próximo, para fins de controle.

**Comment by iuriguilherme** [comment]
As perguntas supracitadas já foram encaminhadas ao [grupo de telegram de construção do site](https://telegram.me/apoiopirata).

Em relação ao conceito de FAQ, não só estamos bem esclarecidos como surgiu [iniciativa para fazer um FAQ amplo e irrestritivo](https://github.com/piratas/gti/issues/35).

**Comment by kannonsan** [comment]
E mais uma vez uma "issue" aqui é fechada sem que tenha sido resolvida.

É a segunda vez que é aberta e fechada uma "issue" sobre problemas e falta de um FAQ funcional no site de apoio.

Quero entender qual a falta de seriedade ou má vontade por parte dos administradores desse site.

**Comment by iuriguilherme** [comment]
Uma lista de perguntas e respostas foi solicitada já e ainda não foi enviada, há esforço desorganizado em reunir algumas delas, e por enquanto não há perspectiva para botar no site.

A ideia original era que as pessoas pudessem colocar lá de forma direta, como o site não foi divulgado, isto não aconteceu, e o FAQ removido.

Nunca houve falta de seriedade ou má vontade por parte das pessoas envolvidas com o site, daí a impossibilidade de ender isto.
