### ISSUE TITLE
Link para o site oficial está errado

### ISSUE THREAD

**Issue by kannonsan** [piratas/apoio-piratas#37]
Em "Fale conosco" o link para o site principal do partido pirata está https://partidopirata.org
Entretanto o SSL não foi inteiramente implementado no site e o acesso por esse link (https) causa quebra na folha de estilos mostrando um site bagunçado,

Para piorar, maior parte dos navegadores se acessar https no lugar de http irá memorizar o endereço errado -- mesmo que depois se mude, retirando o S.

**Comment by iuriguilherme** [comment]
O que foi relatado é um problema na configuração do site do partido, que agora reside em https://github.com/piratas/piratas-site.

Em relação à página supracitada, foi removida do site de apoiamento.
