### ISSUE TITLE
Fazer um design mais decente pro hotsite

### ISSUE THREAD

**Issue by rsip22** [piratas/apoio-piratas#9]

**Comment by carloscosta** [comment]
Eu vou tocar isso. Continuaremos usando o Helpers que é muito bom. Estou adicionando responsividade ao layout (ver 6bd16bf commit). Vou tirar valores fixos dos forms.

**Comment by carloscosta** [comment]
OK, está feito. A idéia geral de simplicidade prevaleceu. A landing page está responsiva, equilibrada e racional. Obrigado!
